apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-test-triggerbinding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: namespace
      value: tekton-pipelines
    - name: gitrepositoryurl
      value: $(body.project.git_http_url)
    - name: projectname
      value: $(body.project.name)